### ISSUE TITLE
Unable to `rbytes publish`

### ISSUE THREAD

**Issue by petrosp** [palkan/rbytes#1]
## What did you do?
Under the gem's root:  

```shell
RAILS_BYTES_ACCOUNT_ID=aaa \
RAILS_BYTES_TOKEN=bbb \
RAILS_BYTES_TEMPLATE_ID=ccc \
rbytes publish path/to/template
```

## What did you expect to happen?
Get:

```
Published successfully ✅
```

## What actually happened?
Got:
```
Failed to publish template: 404 — Not Found
```
## Additional context
It seems that some ENV vars are defined...
https://github.com/palkan/rbytes/blob/523b0f3bcd218310345cd8fd3c006f8965ed5f1c/lib/ruby_bytes/publisher.rb#L9

..but not picked up:

https://github.com/palkan/rbytes/blob/523b0f3bcd218310345cd8fd3c006f8965ed5f1c/lib/ruby_bytes/publisher.rb#L30 

## Environment

**Ruby Version:** 3.2.1

**Framework Version (Rails, whatever):** vanilla

**Rbytes Version:** 0.1.3

**Comment by palkan** [comment]
Thanks for reporting!

Looks like I hard-coded my token 🤦‍♂️ That's why it worked for me)

Fixed in 0.1.4
